### ISSUE TITLE
Pick and choose features?

### ISSUE THREAD

**Issue by Toadby** [emipa606/EveryoneIsQueer#1]
Hi~
Would you consider adding settings to enable or disable different features of this mod? I would love to be able to choose which changes to use in my game.
I am looking into adding the options myself, but I wanted to check if this is something you're interested in as the current custodian of this mod :) Also I have no experience with RimWorld modding so I'm probably not the best person to be adding this feature....
Anyway let me know! Thanks for keeping the mod updated ^^

**Comment by emipa606** [comment]
Since I havent used the mod, what type of settings did you have in mind?

**Comment by Toadby** [comment]
I was thinking to separate each major feature to be disabled/enabled. So toggles for:
- Everyone is bisexual
- Age interest doesn't depend on gender
- Removes bias toward men proposing

Stuff like customizing ratio of sexualities, or customizing age range of interest, would probably be more difficult to implement, but I think these toggles would be nice so people can choose what features rather than making separate mods. I hope that makes sense!

**Comment by emipa606** [comment]
I looked through the mod and unfortunatly adding settings is not possible without rewriting parts of the mod, since parts are done in patches and parts in c#. I dont have time for larger projects but the source is open so feel free to make changes of your own or place a comission on the mod-market discord.
